### ISSUE TITLE
UnboundLocalError: local variable 'img' referenced before assignment

### ISSUE THREAD

**Issue by apawar1199** [CCNYRoboticsLab/pytorch_Concrete_Inspection#1]
C:/Users/apawa/Desktop/pytorch_Concrete_Inspection-master/SPallData/deepLearningBridgeInspectionspallSUbImageForTRaining/imageClustersV130B130/accepted/accept231068.jpg
    train_logger, train_batch_logger, criterion_pose)
  File "C:\Users\apawa\Desktop\py\train.py", line 53, in train_epoch
    for i, (input_imgs, targets) in enumerate(data_loader):
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\apawa\Anaconda3\envs\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\apawa\Desktop\py\make_my_data.py", line 123, in __getitem__
    sour_img = torch.Tensor(torch.from_numpy(img).float().div(255))
UnboundLocalError: local variable 'img' referenced before assignment

**Comment by ccny-ros-pkg** [comment]
Can you confirm your version of Pytorch and python?
